export type CanMatchParams = {
  from: object;
  to: object;
  volume: number;
  content_value?: number;
};

export type CreateParams = {
  description: string;
  from_lat?: number;
  to_lat?: number;
  from_lng?: number;
  to_lng?: number;
  from_address?: string;
  to_address?: string;
  from_postal_code?: string;
  to_postal_code?: string;
  from_pickup_date: string;
  to_pickup_date: string;
  is_packaged: boolean;
  is_passenger: boolean;
  from_is_flexible: boolean;
  to_is_flexible: boolean;
  content_value?: number;
  with_insurance?: boolean;
  price?: number;
  volume?: number;
  environment?: string;
  ride_extra_information?: string;
  from_need_help?: boolean;
  from_need_help_floor?: boolean;
  from_need_help_elevator?: boolean;
  from_need_help_furniture_lift?: boolean;
  to_need_help?: boolean;
  to_need_help_floor?: boolean;
  to_need_help_elevator?: boolean;
  to_need_help_furniture_lift?: boolean;
  ride_objects_attributes?: any[any];
  ride_delivery_information_attributes: any[any];
  photos?: string[];
  external_id?: string;
  photo_urls?: string[];
};

export type CanMatch = {
  result: boolean;
  estimated_prices: {
    regular: number;
    with_insurance: number | null;
  };
  insurance_detail: {
    amount: number;
    conditions_url: string;
  };
  rider_count: number;
};

export type Ride = {
  id: number;
  created_at: string;
  updated_at: string;
  owner_status: string;
  state: 'published' | 'api_pending' | 'deleted' | 'in_progress' | 'completed' | 'expired';
  ga_sent: boolean | null;
  deleted_at: string | null;
  offers_count: number;
  previous_pay_in: boolean;
  conversations: {
    count: number;
    unreaded_messages: number;
  };
  owner: {
    id: number;
    nickname: string;
    gender: string;
    phone_verified: boolean;
    role: string;
    email_verified: boolean;
    sign_up_finished: boolean;
    last_sign_in_at: string | null;
    business_name: string | null;
    avatar: string | null;
    identity_validated: boolean;
  };
  billing_documents: {
    buyer: string;
    seller: string;
  };
  buyer_tracking: string;
  seller_tracking: string;
  title: string;
  description: string;
  from_lat: number | null;
  to_lat: number | null;
  from_lng: number | null;
  to_lng: number | null;
  from_address: string | null;
  to_address: string | null;
  from_postal_code: string | null;
  to_postal_code: string | null;
  from_pickup_date: string;
  to_pickup_date: string;
  is_packaged: boolean;
  is_passenger: boolean;
  from_is_flexible: boolean;
  to_is_flexible: boolean;
  content_value: number;
  with_insurance: boolean;
  price: number | null;
  seller_participation: number | null;
  volume: number;
  environment: string | null;
  rider_extra_information: string | null;
  from_need_help: boolean;
  from_need_help_floor: number;
  from_need_help_elevator: boolean;
  from_need_help_furniture_lift: boolean;
  to_need_help: boolean;
  to_need_help_floor: number;
  to_need_help_elevator: boolean;
  to_need_help_furniture_lift: boolean;
  ride_objects_attributes: Array<{
    title: string;
    qty: number;
    format: string;
    weight: number;
    external_url: string;
  }>;
  ride_delivery_information_attributes: {
    from_address: string;
    from_postal_code: string;
    from_city: string;
    from_country: string;
    from_contact_name: string;
    from_contact_email: string;
    from_contact_phone: string;
    from_extra_information: string;
    to_address: string;
    to_postal_code: string;
    to_city: string;
    to_country: string;
    to_contact_name: string;
    to_contact_email: string;
    to_contact_phone: string;
    to_extra_information: string;
    insurance_firstname: string;
    insurance_lastname: string;
    insurance_address: string;
    insurance_postal_code: string;
    insurance_city: string;
    insurance_country: string;
    insurance_birthdate: string;
  };
};
